### ISSUE TITLE
Localization: 'hard-coded' strings 

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica-directory#14]
Some strings, it appears, cannot be localised.

In the French localization (right side, top corner) "Language" appears to remain in English. https://dir.hubup.pro/?lang=fr

In the Czech localization, same as with French, plus "Forums" and "People" in the centre tabs. https://dir.hubup.pro/?lang=cs Identical situation for Thai (my local version, not yet pushed) see https://dir.hubup.pro/?lang=th

Over at your server French doesn't seem to work at the moment at all. https://dir.friendica.mrpetovan.com/?lang=fr_FR

I'm at https://github.com/friendica/friendica-directory/commit/dd60b60e997136e8bb08afa540525df528f5b096

**Comment by MrPetovan** [comment]
I just fixed the "Language" string in 2505436796580eaaddf3f19c56a3fe2cf227cd14

And the account type tabs have been added to the translation strings in 4dad98fa04e4cb185183da6963d4db29b5609ceb, not sure why you didn't find them while translating.

**Comment by AndyHee** [comment]
>I just fixed the "Language" string in 2505436

Great!

For the account type, I think I didn't fully understand this. I'll check it again tomorrow.

**Comment by MrPetovan** [comment]
The added translation strings just didn't make it to Transifex yet. You can manually edit the up-to-date PO files in `src/lang/th/LC_MESSAGES/strings.po`  with Poedit (https://poedit.net) if you want cutting edge translation.

Process:
- Pull the latest `master`
- Run `bin/console extract-strings th`
- Open `src/lang/th/LC_MESSAGES/strings.po` with Poedit
- Save when you're done
- Commit both PO and MO files

**Comment by AndyHee** [comment]
Fixed by  MrPetovan in https://github.com/friendica/friendica-directory/commit/2505436796580eaaddf3f19c56a3fe2cf227cd14
