### ISSUE TITLE
Add /servers/surprise endpoint

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica-directory#15]
This path redirect to a random server registration page.

Current criterion:
- More than 5 known users in the directory
- Health score greater than 20
- REGISTER_OPEN
- SSL enabled
- Among the top 10 according to this sorting criterion: `((KnownUsers / 100) + 10) * HealthScore`

**Comment by annando** [comment]
Possibly there should also be some load balancing so that top one is never chosen?

**Comment by MrPetovan** [comment]
The rules are pretty complicated as it is, but we can exclude the first server from the ten relevant servers before the actual random part happens.

**Comment by MrPetovan** [comment]
I ended up choosing a server at random among the highest scoring servers with open registration and above 75 health. I forgot about this issue so I didn't incorporate the SSL bit nor the number of known users.

**Comment by MrPetovan** [comment]
Implemented in https://github.com/friendica/friendica-directory/commit/d0102327c08d36107f8047062c89963f12088910

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica-directory/commit/1bbe4d328995bffe3c005277c9cc3256e4bdb944
