### ISSUE TITLE
zrl parameter don't get transmitted to the profile pages

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica-directory#24]
If a user opens the global directory link from inside friendica a `zrl` parameter with the the profile address of  the user is passed to the global directory. This `zrl` parameter should be also added if the user opens a profile url from inside the global directory.

The issue affects https://dir.friendica.social
Friendica Directory version 2.1.1

**Comment by MrPetovan** [comment]
Thanks, I forgot about this parameter.
