### ISSUE TITLE
Nodes with registration policy "requires approval" should be listed

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica-directory#28]
I hope this is the right place to report issues for the directory.

### Expected behavior
Nodes with registration policy "requires approval" should be listed on the directory's server list.

### Actual wrongdoing
Nodes with registration policy "requires approval" are **not** listed on the directory's server list. Which is kind of confusing because the nodeinfo says "openRegistrations: true" and the node is therefore listed as 'open' on the-federation.info/friendica but not on our own directory.

### Steps to reproduce
Set registration policy to "requires approval" and check your nodeinfo and (after some time) the server list on your configured global directory server.

### Directories used for testing
dir.libranet.de 2.2.1
dir.friendica.social 2.2.1

### Friendica used for testing
libranet.de 2019.03
mordor.social 2019.03

### PHP/SQL
PHP 7.2.15 / MariaDB 10.1.38

**Comment by AlfredSK** [comment]
@MrPetovan What do you think? Would it be good enough to simply change the queries from ``WHERE `reg_policy` = "REGISTER_OPEN"`` to ``WHERE `reg_policy` != "REGISTER_CLOSED"``?

I did that in my own directory locally and it seems to work.
https://dir.libranet.de/servers

If you agree I'll do a PR on the weekend.

**Comment by MrPetovan** [comment]
Absolutely.

**Comment by AlfredSK** [comment]
Thanks for checking your GitHub notifications. :-)

**Comment by AndyHee** [comment]
Nice one @AlfredSK !

**Comment by AlfredSK** [comment]
I created the PR #35 :-)
