### ISSUE TITLE
Cap Score for Servers Without Description 

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica-directory#34]
I think public servers that do not provide a description should not be listed in the higher rankings.

New users should be able to get some idea about the node they sign up to. It may look that the admin inadvertently opened their node without somehow being committed to provide such service.

This may be even more important with @AlfredSK 's upcoming enhancement  https://github.com/friendica/friendica-directory/issues/28

I suggest a cap of "**75**".

**Comment by MrPetovan** [comment]
Good idea.
