### ISSUE TITLE
Labels to Distinguish Different Registration Policies: "Register Open" and "Register by Approval" 

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica-directory#36]
With the improved listing of public servers https://github.com/friendica/friendica-directory/pull/35 , we should clearly label nodes with that have an  "Open" and "Closed" registration policy.

**Comment by MrPetovan** [comment]
"Open" and "Approve", no?

**Comment by AlfredSK** [comment]
> "Open" and "Approve", no?

Yes. :-) Closed nodes don't show up in the server list.

**Comment by AndyHee** [comment]
> "Open" and "Approve", no?

Yes, that's what I meant. Sorry about the confusion.
