### ISSUE TITLE
Server health score calculation overwrites $max_health if server is dev or rc

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica-directory#53]
In src/Classes/Pollers/Server.php, at lines 370/371 in function computeHealthScore, if server's version is dev or RC, previous settings of $max_health are overwritten with $max_health = 95.  

I have "fixed" this with this chunk of very-possibly-an-inefficient-way-of-doing-this:

```
$old_max_health = $max_health;
$new_max_health = 95; //Develop/RC can be unstable
$max_health = min($old_max_health, $new_max_health);
```

**Comment by MrPetovan** [comment]
This looks good, do you want to submit a PR in your name?

**Comment by realkinetix** [comment]
I guess I probably should!  I'll get on that.

**Comment by realkinetix** [comment]
Thank you for forcing me to practice git!

**Comment by MrPetovan** [comment]
Thank you for your work!
