### ISSUE TITLE
Your configuration indicates the merge with reference 'refs / heads / master' of the remote repository

### ISSUE THREAD

**Issue by ghost** [friendica/friendica-directory#69]
Getting this after a git pull

`Your configuration indicates the merge with reference 'refs / heads / master' of the remote repository, but this reference was not requested.
`

**Comment by tobiasd** [comment]
Which branch are you using? `git branch` will list them all and your current one will be marked with an `*`

**Comment by MrPetovan** [comment]
You don't need to worry about this, it will show once because the master branch has been deleted, and it won't show ever again. Just use the `stable` branch.

**Comment by ghost** [comment]
Okay i changed it from master to stable and now it update database cheme from 5 to 8
