### ISSUE TITLE
Site-level noscrape

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica-directory#7]
From https://github.com/friendica/dir/issues/9
>Build in support for using noscrape to pull a full list of profiles that should be in the directory.
> This way we do not need to sync individual profiles, but we can sync full sites at a time.

**Comment by annando** [comment]
See here: https://forum.friendi.ca/display/ec054ce7-895b-e91e-c077-60d759826506

**Comment by MrPetovan** [comment]
Good, but it isn't ready yet, right?

**Comment by annando** [comment]
Partly.

**Comment by MrPetovan** [comment]
Can I start using it from the directory or is the format subject to change?

**Comment by annando** [comment]
The format will stay the same. Just make sure to add all needed fields in the query parameter, see this example:

```?fields=displayName,urls,photos,updated,network,aboutMe,currentLocation,tags,gender,contactType,generation```

The thing that will most likely change is that more accounts will be exported.

**Comment by MrPetovan** [comment]
I just need the profile URL to add them to the poll queue, the background task takes care of the rest.

**Comment by MrPetovan** [comment]
Sample output for https://friendica.mrpetovan.com/poco?fields=urls
```json
{
	"startIndex": 0,
	"itemsPerPage": 1,
	"totalResults": 1,
	"entry": [{
		"urls": [{
			"value": "https:\/\/friendica.mrpetovan.com\/profile\/friendicafr",
			"type": "profile"
		}, {
			"value": "acct:friendicafr@friendica.mrpetovan.com",
			"type": "webfinger"
		}]
	}]
}
```

**Comment by annando** [comment]
Why don't you fetch all these fields in total?

**Comment by MrPetovan** [comment]
1. Because I already have a way of retrieving all the necessary fields from the `/noscrape` endpoint.
2. To go easier on nodes.
